services:
  - type: web
    name: my-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: my-postgres
          property: connectionString

databases:
  - name: my-postgres
    plan: free

          property: password

databases:
  - name: agency-db
    plan: free
